# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "../" # Location of package manifests
    registries: "*" # or tfc-herbalife
    # target-branch: "feat/grouping-prs-for-multiple-version-update"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "US/Pacific"
    groups:
      providers:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
