version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    allow:
      - dependency-type: "all"
    groups:
      dev-providers-patch-minor:
        patterns:
          - "*"
        update-types:
        - "minor"
        - "patch"
        exclude-patterns:
          - "*module*"
      dev-modules-patch-minor:
        patterns:
          - "*"
        update-types:
        - "minor"
        - "patch"
        exclude-patterns:
          - "*provider*"
      dev-providers-major:
        patterns:
          - "*"
        update-types:
        - "major"
        exclude-patterns:
          - "*module*"
      dev-modules-major:
        patterns:
          - "*"
        update-types:
        - "major"
        exclude-patterns:
          - "*provider*"
