version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dev-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
      dev-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/qa"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:35"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      qa-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
      qa-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/stg"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:40"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      stg-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
      stg-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/uat"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:45"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      uat-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
      uat-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
