version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dev-providers-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
        exclude-patterns:
          - "*module*"
      dev-providers-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
        exclude-patterns:
          - "*module*"
