# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    allow:
      dependency-type: "all"
    ignore:
      update-types: ["version-update:semver-major"]
    groups:
      dev-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
        update-types:
          - "patch"
          - "minor"
      dev-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/qa"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:35"
      timezone: "America/Mexico_City"
    groups:
      qa-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
        update-types:
          - "patch"
          - "minor"
      qa-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/stg"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:40"
      timezone: "America/Mexico_City"
    groups:
      stg-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
        update-types:
          - "patch"
          - "minor"
      stg-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/uat"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:45"
      timezone: "America/Mexico_City"
    groups:
      uat-providers:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
        update-types:
          - "patch"
          - "minor"
      uat-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
        update-types:
          - "patch"
          - "minor"
