version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      dev-providers-patch:
        patterns:
        - "*tfe*"
        update-types:
        - "patch"
        exclude-patterns:
        - "*module*"
