version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
    groups:
      dev-providers-patch:
        patterns:
          - "google"
          - "tfe"
        update-types:
          - "patch"
        exclude-patterns:
          - "*module*"
