version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    groups:
      dev-providers-minor:
        patterns:
          - "*"
        exclude-patterns:
          - "*module*"
        update-types: 
          - "minor"
          - "major"
      dev-modules-minor:
        patterns:
          - "*"
        exclude-patterns:
          - "*provider*"
        update-types: 
          - "minor"
          - "major"
