version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    allow:
      - dependency-type: "direct"
    groups:
      dev-providers-patch:
        patterns:
        - "tfe"
        - "google"
        update-types:
        - "patch"
        exclude-patterns:
        - "*module*"
      dev-providers-minor:
        patterns:
        - "tfe"
        - "google"
        update-types:
        - "minor"
        exclude-patterns:
        - "*module*"
      dev-providers-major:
        patterns:
        - "tfe"
        - "google"
        update-types:
        - "major"
        exclude-patterns:
        - "*module*"
