version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:30"
      timezone: "America/Mexico_City"
    groups:
      dev-providers-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
        exclude-patterns:
          - "*module*"
      dev-providers-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
        exclude-patterns:
          - "*module*"
      dev-providers-major:
        patterns:
          - "*"
        update-types:
          - "major"
        exclude-patterns:
          - "*module*"
